CREATE TABLE ANIMAL(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	ESPECIE VARCHAR(100) NOT NULL,
	RAÇA VARCHAR(100) NOT NULL,
	COR VARCHAR(100) NOT NULL,
	SEXO BOOLEAN NOT NULL,
	DATA_DE_NASCIMENTO INTEGER,
	CASTRADO BOOLEAN NOT NULL,
	DATA_CASTRADO INTEGER,
	RG INTEGER,
	MICROCHIP INTEGER,
	PAI VARCHAR(100) NOT NULL,,
	MAE VARCHAR(100) NOT NULL,,
	CADB INTEGER
);

CREATE TABLE PROPIETARIO(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	ENDEREÇO VARCHAR(100) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	CEP VARCHAR(100) NOT NULL,
	DATA_DE_NASCIMENTO INTEGER NOT NULL,
	EMAIL  VARCHAR(150) NOT NULL UNIQUE,
	SENHA  VARCHAR(6) NOT NULL UNIQUE,
	TEL INTEGER NOT NULL,
	CEL INTEGER NOT NULL,
	RG INTEGER NOT NULL,
	CPF INTEGER NOT NULL,
	);

CREATE TABLE VETERINARIO(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	ENDEREÇO VARCHAR(100) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	CEP  INTEGER NOT NULL,
	EMAIL  VARCHAR(150) NOT NULL UNIQUE,
	SENHA  VARCHAR(6) NOT NULL UNIQUE,
	SEXO BOOLEAN NOT NULL,
	DATA_DE_NASCIMENTO INTEGER NOT NULL,
	TEL INTEGER NOT NULL,
	CEL INTEGER NOT NULL,
	RG INTEGER NOT NULL,
	CPF INTEGER NOT NULL,
	EMERGENCIA INTEGER NOT NULL
);